ewaol-tests: Fix direct execution of run-*-integration-tests
We need to ensure that we don't run bats from the current user ${HOME} to
avoid permission denied error, since at some point it will `cd "$OLDPWD"`
when we already switched to ${EWAOL_TEST_ACCOUNT} via the sudo command.

Issue-Id: SCM-4394
Signed-off-by: Diego Sueiro <diego.sueiro@arm.com>
Change-Id: Ibf13cb577b6dbbef6c2e6242063265fff94c8a08

diff --git a/meta-ewaol-tests/recipes-tests/runtime-integration-tests/files/run-test-suite b/meta-ewaol-tests/recipes-tests/runtime-integration-tests/files/run-test-suite
--- a/meta-ewaol-tests/recipes-tests/runtime-integration-tests/files/run-test-suite
+++ b/meta-ewaol-tests/recipes-tests/runtime-integration-tests/files/run-test-suite
@@ -4,6 +4,15 @@
 #
 # SPDX-License-Identifier: MIT
 
+# We need to ensure that we don't run bats from the current user ${HOME} to
+# avoid permission denied error, since at some point it will `cd "$OLDPWD"`
+# when we already switched to ${EWAOL_TEST_ACCOUNT} via the following sudo
+# command.
+if ! cd /home ; then
+    echo "FAIL:${TEST_SUITE_NAME}"
+    exit 1
+fi
+
 if sudo -HEnu "${EWAOL_TEST_ACCOUNT}" bats "${TEST_DIR}/${TEST_SUITE_NAME}.bats"; then
     echo "PASS:${TEST_SUITE_NAME}"
     exit 0
